name: '$(Date:yy.)$(Date:MM.)$(Date:dd.)$(rev:rr)_$(SourceBranchName)'

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

parameters:
- name: DotNetVersion
  default: net6.0
  values:
  - net6.0
  - net8.0
- name: overwrite
  type: boolean
  default: false
- name: publishWebProjects
  type: boolean
  default: false
- name: projectFile
  type: string
  default: app_name/app_name.csproj
- name: solution
  type: string
  default: app_name/app_name.sln
- name: nugetFeed
  type: string
  default: 59388b54-2798-4d11-b0d7-a731a1308e1e
- name: buildArgs
  type: string
  default: /p:Configuration=Release -m
- name: testProject
  type: string
  default: '**/*.Tests.csproj'
- name: publishPath
  type: string
  default: $(Build.ArtifactStagingDirectory)
- name: artifactName
  type: string
  default: drop
- name: buildConfiguration
  type: string
  default: 'Release'
- name: outputDir
  type: string
  default: $(Build.ArtifactStagingDirectory)

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: BuildAndTest
      displayName: 'Build, Test, and Publish .NET Application'
      steps:
            
        # Clear NuGet Cache
        - script: nuget locals all -clear
          displayName: 'Clear NuGet Cache'

        # Restore NuGet Packages
        - task: DotNetCoreCLI@2
          displayName: 'Restore NuGet Packages'
          inputs:
            projects: ${{ parameters.solution }}
            feedsToUse: 'select'
            vstsFeed: ${{ parameters.nugetFeed }}

        # Build the Solution
        - task: DotNetCoreCLI@2
          displayName: 'Build Solution'
          inputs:
            command: build
            projects: ${{ parameters.solution }}
            arguments: '--configuration ${{ parameters.buildConfiguration }}'

        # Publish the Project
        - task: DotNetCoreCLI@2
          displayName: 'Publish Project'
          inputs:
            command: publish
            projects: ${{ parameters.solution }}
            arguments: '--configuration ${{ parameters.buildConfiguration }} --output ${{ parameters.outputDir }} -f ${{ parameters.DotNetVersion }}'
            publishWebProjects: false

        # Publish Artifacts
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Build Artifacts'
          inputs:
            targetPath: ${{ parameters.publishPath }}
            artifactName: ${{ parameters.artifactName }}

- stage: CopyFiles
  displayName: 'Copy Files Stage'
  jobs:
    - job: Copy_Job
      displayName: 'Copy Files to Target Directory'
      pool:
        name: 'Agent Pool'
      steps:
        # Download the Build Artifacts from the previous stage
        - task: DownloadPipelineArtifact@2
          displayName: 'Download Build Artifacts'
          inputs:
            artifactName: ${{ parameters.artifactName }}
            targetPath: ${{ parameters.publishPath }}
        - task: CopyFiles@2
          displayName: 'Copy Files'
          inputs:
            SourceFolder: ${{ parameters.publishPath }}
            Contents: '**'
            TargetFolder: \\SERVER_NAME\TEST_MESSIMER_PIPELINES_DEPLOY\APP_NAME
            OverWrite: $(overwrite)
            flattenFolders: false
          continueOnError: false
